### ISSUE TITLE
Create an new endpoint /api/user{id}/fundraisers

### ISSUE THREAD

**Issue by RuslanKuchmynda** [ezbir/ezbir-be#1]
Створити endpoint `/api/user{id}/fundraisers` в якому можна буде получити весь список зборів конкретного користувача

**Comment by RuslanGren** [comment]
[src/main/java/com/ua/ezbir/web/controllers/FundraiserController.java](https://github.com/ezbir/ezbir-be/commit/06da5cbd728f6b47b3ea839684de8f8f82353cf2#diff373e6e90073045f88736d1c58edd92b79fad2af3e55416c4c4fbc1cc9506b8ea)
`@GetMapping("/{id}")
    public FundraiserResponseDto findFundraiserById(
            @PathVariable("id") Long id
    ){
        return fundraiserService.getFundraiserResponseDto(id);
    }
`
